"""Project-wide configuration constants."""

from .drone import (
    COOLDOWN_SECONDS,
    DYNAMIC_MODEL_PATH,
    LANDMARKER_MODEL_PATH,
    PRED_THRESHOLD_DYNAMIC,
    PRED_THRESHOLD_STATIC,
    STATIC_MODEL_PATH,
    VELOCITY_FACTOR_X,
    VELOCITY_FACTOR_Y,
    VELOCITY_FACTOR_Z,
)
from .dynamic import (
    CHANNELS,
    COLORS,
    DATA_PATH,
    DYNAMIC_DIR,
    EPOCHS,
    INPUT_SHAPE,
    LEARNING_RATE,
    LOG_DIR,
    LOSS,
    MAX_SENTENCE_LENGTH,
    METRICS,
    MODEL_PATH,
    NO_SEQUENCES,
    NUM_NODES,
    OPTIMIZER,
    PROJECT_ROOT,
    SEQUENCE_LENGTH,
    STABLE_LENGTH,
    TEST_SIZE,
    THRESHOLD,
)
from .gestures import DYNAMIC_ACTIONS, STATIC_HAND_GESTURES
from .mpParameters import MIN_DETECTION_CONFIDENCE, MIN_TRACKING_CONFIDENCE